### ISSUE TITLE
Add credential-Entity for better testing, encapsulation and persistence stuff

### ISSUE THREAD

**Issue by rabbl** [MichaelThessel/pwx#32]
It would be fine to have an entity-Object for the credential stuff. Brings the following benefits:
- Encapsulation of User and Password-Data
- Better testing experience 
- TypeHinting in services
- Database and schema-creation by doctrine and possibility to user other DBs like postgres, mongo, sqlite, etc.

I think there are many other benefits.

The properties could be:
- hash
- usernamePlainText
- username
- passwordPlaintext
- password
- commentPlainText
- comment
- email (https://github.com/MichaelThessel/pwx/issues/28)
- expiresAt

Where the plaintext properties won't be persisted.
Then you can pipe this entity easy through encrypting and decrypting services.

Here is an old and informative example with the use of annotations and CLI:
http://ahoj.io/silex-doctrine2-orm

**Comment by MichaelThessel** [comment]
Sounds good to me. Feel free to go ahead with it. I'm using Doctrine ORM for pretty much all my custom PHP projects. It seemed overkill for PWX at the time but I don't think it would hurt to add it. I definitely see the testing benefits.

**Comment by rabbl** [comment]
I'm working on this issue in the fork: https://github.com/rabbl/pwx/tree/issue_32
Until now I added the [Doctrine-ORM-Service-Provider](https://github.com/dflydev/dflydev-doctrine-orm-service-provider)

The config in app.php got some more [parameter](https://github.com/rabbl/pwx/blob/issue_32/app/app.php#L23)

Added [Credentials Entitiy and EntityRepository](https://github.com/rabbl/pwx/tree/issue_32/src/App/Entity).

To not confuse, the name of the table is: entity_credentials_table

The following commands are working:
app/console orm:schema-tool:create
app/console orm:schema-tool:update --force
app/console orm:schema-tool:drop --force

**Comment by MichaelThessel** [comment]
Some comments:

**Comment by MichaelThessel** [comment]
Some comments:
- Doctrine supports [Event Listeners](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/events.html#implementing-event-listeners). Instead of having 2 attributes for each attribute in the entity you could use the postLoad and preUpdate event listeners to de/encrypt the data. That way you wouldn't need the plainText entities. Alternatively you could use the getter and setter functions for that. 
- We don't need an id and hash attribute. Hash as primary key should be fine.
- Till we add the email functionality no need to add an attribute for it. Better not to have lose ends.
- Same for the oneTimeView
- We don't need the expired attribute. Entities get deleted automatically when they are expired. [Code](https://github.com/MichaelThessel/pwx/blob/master/src/App/Model/CredentialService.php#L130). That said that functionality is not super pretty. Currently the entities get cleaned on each request. I didn't want to have people run cron for PWX entity cleanup. Might be good to add a cron option in the future. Unless you run a really high volume install it shouldn't be a big deal.

**Comment by MichaelThessel** [comment]
~~Alternatively you could use the getter and setter functions for that~~, don't actually do that. That would require an additional local cache. Otherwise you would need to de/encrypt every time.

**Comment by rabbl** [comment]
In https://github.com/rabbl/pwx/commit/e9f8aa2eb6b2e79731034c50c1a5f2e5d4b8a4e6 I made the proposed entity changes.
The SQL to create the table is almost the same by now.

``` sql
CREATE TABLE entity_credentials_table (
    hash VARCHAR(10) DEFAULT '' NOT NULL,
    username LONGTEXT NOT NULL, 
    password LONGTEXT NOT NULL, 
    comment TEXT NOT NULL, 
    expiresAt DATETIME NOT NULL, 
    PRIMARY KEY(hash)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
```

**Comment by MichaelThessel** [comment]
That looks good so far. Just one comment.
Don't suffix the table name with _table. I usually don't add the @table annotation at all and leave it to Doctrine to name the tables. It will give the table the same name as the class name.

**Comment by MichaelThessel** [comment]
Once we got the Doctrine ORM fully in place, we can remove the install folder with the example SQL and update the documentation to use the Doctrine command line client to create the table.

**Comment by MichaelThessel** [comment]
I merged the pull request. I had to do some changes. Some of the patterns were not 100% correct. Those are the changes I did 3803ae1985d3d02e8cf70395ed220f0ccfa06f0c. The main change is that I removed the encryption service again. I went with an abstract class that inherits from an encryption class instead. This class takes care of the encryption of entities automatically.
